#
# Docker Compose
# created/edit 31.12.2016 by T.H.
# PASSWORD: root/postgres:passw0rd (PLEASE CHANGE THE DEFAULT PASSWORDS!)
# Todo:	
#	sudo mkdir -p /srv/webgis/{mysql,postgresql,geoserver,nginx,ssl,html}
# 	sudo docker-compose up -d
#

webgis-mysql:
  image: mysql/mysql-server:5.6
  environment:
    MYSQL_ROOT_PASSWORD: passw0rd
  #ports:
  #  - "3306:3306"
  volumes:
    - /srv/webgis/mysql:/var/lib/mysql

#webgis-phpmyadmin:
#  image: phpmyadmin/phpmyadmin:latest
#  environment:
#    PMA_ABSOLUTE_URI: http://localhost/phpMyAdmin/
#  links:
#    - "webgis-mysql:db"
#  #ports:
#  #  - "8306:80"

webgis-postgresql:
  #image: postgres:latest
  image: mdillon/postgis:latest
  environment:
    POSTGRES_PASSWORD: passw0rd
  #ports:
  #  - "5432:5432"
  volumes:
    - /srv/webgis/postgresql:/var/lib/postgresql/data

#webgis-phppgadmin:
#  image: superkul/phppgadmin:latest
#  links:
#    - "webgis-postgresql:postgres"
#  #ports:
#  #  - "8432:80"

webgis-geoserver:
  image: kartoza/geoserver:latest
  links:
    - "webgis-postgresql:postgis"
  ports:
    - "8080:8080"
  volumes:
    - /srv/webgis/geoserver:/opt/geoserver/data_dir

webgis-phpapache:
  #image: php:5.6-apache
  image: tobi312/php:5.6-apache
  environment:
    TZ: "Europe/Berlin"
    PHP_ERRORS: 1
    PHP_UPLOAD_MAX_FILESIZE: 250
    ENABLE_REWRITE: 1
    ENABLE_SSL: 1
    ALLOWOVERRID: 1
    REMOTEIP: 1
  links:
    - "webgis-mysql:mysql"
    - "webgis-postgresql:postgresql"
  #ports:
  #  - "80:80"
  #  - "443:443"
  volumes:
    - /srv/webgis/html:/var/www/html
    #- /etc/localtime:/etc/localtime:ro
    #- /srv/webgis/ssl:/etc/ssl:ro

webgis-nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  links:
    #- "webgis-phpmyadmin:phpmyadmin"
    #- "webgis-phppgadmin:phppgadmin"
    - "webgis-geoserver:geoserver"
    - "webgis-phpapache:phpapache"
  volumes:
    - /srv/webgis/nginx:/etc/nginx/conf.d:ro
    - /srv/webgis/ssl:/etc/nginx/ssl:ro
    #- /srv/webgis/html:/var/www/html:ro
