#
# Docker Compose
# created 02.08.2017 by T.H.
# Todo:	
#	Change PASSWORD: root/postgres:passw0rd (PLEASE CHANGE THE DEFAULT PASSWORDS!)
#	Change Domain and E-Mail for Lets Encrypt
#	sudo mkdir -p /srv/webgis/{mysql,postgresql,geoserver,nginx,ssl,html,letsencrypt}
#	sudo docker-compose up -d
#

version: "2.0"

services:

  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    #ports:
    #  - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      webgis:
        aliases:
         - db
  
  postgresql:
    #image: postgres:latest
    image: mdillon/postgis:9.6
    environment:
      POSTGRES_PASSWORD: passw0rd
    #ports:
    #  - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      webgis:
        aliases:
         - postgis
         - postgres
  
  geoserver:
    image: kartoza/geoserver:latest
    #ports:
    #  - "8088:8080"
    volumes:
      - ./geoserver:/opt/geoserver/data_dir
    networks:
      webgis:
  
  phpapache:
    #image: php:7.0-apache
    image: tobi312/php:7.0-apache
    environment:
      TZ: "Europe/Berlin"
      PHP_ERRORS: 1
      PHP_UPLOAD_MAX_FILESIZE: 250
      ENABLE_REWRITE: 1
      ENABLE_SSL: 1
      REMOTEIP: 1
    #ports:
    #  - "8080:80"
    #  - "8443:443"
    volumes:
      - ./html:/var/www/html
    #  - ./ssl:/etc/ssl:ro
    networks:
      webgis:
  
  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    command:  bash -c "sleep 6 && certbot certonly --standalone -d __DOMAIN__ -d __DOMAINwithWWW__ --email __YOUR-EMAIL__ --text --agree-tos --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
    entrypoint: ""
    #ports:
    #  - "80:80"
    #  - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    #  - /var/lib/letsencrypt
    environment:
      - TERM=xterm
    networks:
      webgis:
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./ssl:/etc/nginx/ssl:ro
    #  - ./html:/var/www/html:ro
    networks:
      webgis:

networks:
  webgis:
  
#volumes:
#  letsencrypt-data:
