## BasicAuth

## https://doc.traefik.io/traefik/middlewares/http/basicauth/ (Tabs: Kubernetes)
apiVersion: traefik.containo.us/v1alpha1   # not work: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: default
spec:
  basicAuth:
    secret: basic-auth
    removeHeader: true

---

## see also ../basic-auth-secret.yaml !
## 
## https://doc.traefik.io/traefik/middlewares/http/basicauth/ (Tabs: Kubernetes)
## https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: default
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4=      # admin     in base64
  password: cGFzc3cwcmQ=  # passw0rd  in base64
