## BasicAuth

## https://doc.traefik.io/traefik/middlewares/http/basicauth/ (Tabs: Kubernetes)
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: kube-system
spec:
  basicAuth:
    secret: basic-auth
    removeHeader: true

---

## see also ../basic-auth-secret.yaml !
## 
## https://doc.traefik.io/traefik/middlewares/http/basicauth/ (Tabs: Kubernetes)
## https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: kube-system
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: passw0rd
