# docker-compose -f mariadb.yml up -d
version: '2.4'
services:

  # MariaDB - relational database (SQL), forked from MySQL
  # https://mariadb.org/
  # https://hub.docker.com/_/mariadb
  # https://github.com/MariaDB/mariadb-docker
  # https://github.com/Tob1asDocker/rpi-mariadb/
  mariadb:
    image: mariadb:10.6                      # Supported architectures: amd64, arm64v8
    # image: tobi312/rpi-mariadb:10.6-alpine # Supported architectures: arm32v7 (RaspberryPi)
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./mariadb-data:/var/lib/mysql:rw
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Europe/Berlin
      #MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_ROOT_PASSWORD: passw0rd
      MARIADB_DATABASE: db
      MARIADB_USER: user
      MARIADB_PASSWORD: passw0rd
      #MARIADB_EXPORTER_PASSWORD: passw0rd
    #entrypoint:
    #  sh -c "
    #    echo \"SET GLOBAL time_zone = '$$TZ'; SET time_zone = '$$TZ'; SELECT CURRENT_TIME; CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY '$$MARIADB_EXPORTER_PASSWORD' WITH MAX_USER_CONNECTIONS 3; GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%'; \" > /docker-entrypoint-initdb.d/init.sql;
    #    /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #  "
    ports:
      - 3306:3306
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1
      #test:  mysqladmin ping -h 127.0.0.1 -u $$MARIADB --password=$$MYSQL_PASSWORD || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
      #start_period: 30s
