# docker-compose -f minecraft-bedrock.yml up -d
version: '2.4'
services:

  # Minecraft - a sandbox video game
  # Minecraft Bedrock Server
  # https://www.minecraft.net/
  # https://hub.docker.com/r/itzg/minecraft-bedrock-server + https://github.com/itzg/docker-minecraft-bedrock-server
  # Supported architectures: amd64
  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server:latest
    container_name: bds
    restart: unless-stopped
    tty: true         # docker run -i
    stdin_open: true  # docker run -t
    volumes:
      - ./minecraft-bedrock-data:/data:rw
    ports:
      - 19132:19132/udp
    #mem_limit: 4g
    #mem_reservation: 512m
    #cpus: 2.0
    environment:
      TZ: Europe/Berlin
      EULA: "TRUE"
      VERSION: "latest"
      #UID: "1000"
      #GID: "1000"
      #PACKAGE_BACKUP_KEEP: "2"
      SERVER_NAME: "Minecraft Bedrock Server"
      #SERVER_PORT: "19132"
      #SERVER_PORT_V6: "19132"
      GAMEMODE: "survival"   # Options: survival, creative, adventure
      DIFFICULTY: "normal"   # Options: peaceful, easy, normal, hard
      LEVEL_TYPE: "DEFAULT"  # Options: FLAT, LEGACY, DEFAULT
      ALLOW_CHEATS: "false"  # Options: true, false
      MAX_PLAYERS: "20"
      ONLINE_MODE: "true" # Options: true, false (removes Xbox Live account requirements)
      #WHITE_LIST: "false" # Options: true, false  # with 1.16.230.50 replace with allow list
      #WHITE_LIST_USERS: "player1,player2,player3"
      ALLOW_LIST: "false" # Starting with 1.16.230.50: Options: true, false 
      #ALLOW_LIST_USERS: "player1,player2,player3"
      #VIEW_DISTANCE: "10"
      #TICK_DISTANCE: "4"
      #PLAYER_IDLE_TIMEOUT: "30"
      #MAX_THREADS: "8"
      LEVEL_NAME: "Minecraft Bedrock Server"
      #LEVEL_SEED: "33480944"
      DEFAULT_PLAYER_PERMISSION_LEVEL: "member" # Options: visitor, member, operator
      TEXTUREPACK_REQUIRED: "false" # Options: true, false
      #SERVER_AUTHORITATIVE_MOVEMENT: ""
      #PLAYER_MOVEMENT_SCORE_THRESHOLD: ""
      #PLAYER_MOVEMENT_DISTANCE_THRESHOLD: ""
      #PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS: ""
      #CORRECT_PLAYER_MOVEMENT: "" # Options: true, false
      OPS: "uuid1,uuid2"
      MEMBERS: "uuid1,uuid2"
      VISITORS: "uuid1,uuid2"
