# docker-compose -f mongo-express.yml up -d
version: '2.4'
services:
  
  # mongo-express - Web-based MongoDB admin interface
  # https://github.com/mongo-express/mongo-express
  # https://hub.docker.com/_/mongo-express + https://github.com/mongo-express/mongo-express-docker
  # Supported architectures: arm64v8, amd64
  # URL: http://localhost:8081/
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    environment:
      # https://github.com/mongo-express/mongo-express-docker#configuration
      # https://github.com/mongo-express/mongo-express#usage-docker
      #ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017"  # if mongo use auth, then comment in and use "ME_CONFIG_MONGODB_URL with auth cred."
      ME_CONFIG_MONGODB_URL: "mongodb://user:passw0rd@mongo:27017"
      ME_CONFIG_OPTIONS_EDITORTHEME: "default"
      #ME_CONFIG_REQUEST_SIZE: "100kb"
      ME_CONFIG_SITE_BASEURL: "/mongo-express/"
      #ME_CONFIG_SITE_SSL_ENABLED: "false"
      #ME_CONFIG_SITE_SSL_CRT_PATH: ""
      #ME_CONFIG_SITE_SSL_KEY_PATH: ""
      #ME_CONFIG_MONGODB_SSLVALIDATE: "true"
      #ME_CONFIG_OPTIONS_READONLY: "false"
      #ME_CONFIG_OPTIONS_NO_DELETE: "false"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: "user"
      ME_CONFIG_BASICAUTH_PASSWORD: "passw0rd"
      #ME_CONFIG_SITE_COOKIESECRET: "cookiesecret"
      #ME_CONFIG_SITE_SESSIONSECRET: "sessionsecret"
      #ME_CONFIG_MONGODB_AUTH_DATABASE: "db"     # only needed if ME_CONFIG_MONGODB_ENABLE_ADMIN is "false"
      #ME_CONFIG_MONGODB_AUTH_USERNAME: "admin"  # only needed if ME_CONFIG_MONGODB_ENABLE_ADMIN is "false"
      #ME_CONFIG_MONGODB_AUTH_PASSWORD: "pass"   # only needed if ME_CONFIG_MONGODB_ENABLE_ADMIN is "false"
    ports:
      - 8081:8081/tcp
    healthcheck:
      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 8081 || exit 1"]
      #start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3