# docker-compose -f mumble.yml up -d
version: '2.4'
services:

  # Mumble - voice-chat software
  # https://www.mumble.info/ + https://github.com/mumble-voip/mumble
  # https://hub.docker.com/r/phlak/mumble + https://github.com/PHLAK/docker-mumble
  # Supported architectures: amd64
  # Password see in logs after start: docker logs mumble-server 2>&1 | grep "Password for 'SuperUser'" 
  #          or set env or set new: docker exec -it mumble-server supw
  mumble:
    image: phlak/mumble:latest    # 1.3.4
    container_name: mumble-server
    restart: unless-stopped
    ports:
      - 64738:64738/udp
      - 64738:64738/tcp
    environment:
      TZ: Europe/Berlin
      SUPERUSER_PASSWORD: passw0rd
    volumes:
      - mumble-data:/etc/mumble:rw
    healthcheck:
      test:  ["CMD-SHELL", "[ \"$$(wget -qO- --no-check-certificate 127.0.0.1:64738 2>&1)\" = \"wget: error getting response\" ] || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
    #  #start_period: 30s

# before start mumble: mkdir ./mumble-data/    
volumes:
  mumble-data:
    driver_opts:
      type: none
      device: ${PWD}/mumble-data
      o: bind
