# docker-compose -f postgres.yml up -d
version: '2.4'
services:
  
  # PostgreSQL - object-relational database (SQL)
  # https://www.postgresql.org/ + https://github.com/postgres/postgres
  # https://hub.docker.com/_/postgres + https://github.com/docker-library/postgres
  # PostGIS - a spatial database extender for PostgreSQL
  # https://postgis.net/ + https://github.com/postgis/postgis/
  # https://hub.docker.com/r/postgis/postgis + https://github.com/postgis/docker-postgis
  # https://github.com/Tob1asDocker/rpi-postgresql-postgis
  postgres:
    image: postgres:14-alpine                           # Supported architectures: arm32v5, arm32v6, arm32v7, arm64v8, amd64
    #image: postgis/postgis:14-3.1-alpine                # Supported architectures: amd64
    #image: tobi312/rpi-postgresql-postgis:14-3.1-alpine # Supported architectures: arm32v7
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    environment:
       TZ: Europe/Berlin
       POSTGRES_PASSWORD: passw0rd
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       #PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 5s
      retries: 5