# docker-compose -f adminer.yml -p adminer up -d
version: '2.4'
services:
  
  # Adminer - Database management in PHP
  # https://www.adminer.org/
  # https://github.com/vrana/adminer/
  # https://hub.docker.com/_/adminer
  # Supported architectures: arm32v6, arm32v7, arm64v8, amd64, ...
  # URL: http://localhost:8080/
  adminer:
    image: adminer:latest
    #image: tobi312/tools:adminer
    container_name: adminer
    restart: unless-stopped
    environment:
      #- ADMINER_DEFAULT_SERVER=db  # default: db
      #- ADMINER_PLUGINS=tables-filter tinymce
      - ADMINER_DESIGN=nette
    #ports:
    #  - 8080:8080/tcp
    healthcheck:
      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 8080 || exit 1"]
      #start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      #- "traefik.docker.network=mynetwork"
      # Tell Traefik to use the http port 8080 to connect to adminer container
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.services.adminer.loadbalancer.server.scheme=http"  # when "https" then set "--serversTransport.insecureSkipVerify=true" for traefik
      # http
      - "traefik.http.routers.adminer-http.rule=Host(`adminer.example.com`)"
      - "traefik.http.routers.adminer-http.entrypoints=web"
      - "traefik.http.routers.adminer-http.service=adminer"
      # https
      - "traefik.http.routers.adminer-https.tls=true"
      - "traefik.http.routers.adminer-https.rule=Host(`adminer.example.com`)"
      - "traefik.http.routers.adminer-https.entrypoints=websecure"
      - "traefik.http.routers.adminer-https.service=adminer"
      # load middlewares for routes
      - "traefik.http.routers.adminer-http.middlewares=adminer-https"
      # http to https redirect      
      - "traefik.http.middlewares.adminer-https.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.adminer-https.redirectscheme.permanent=true"
      #- "traefik.http.middlewares.adminer-https.redirectscheme.port=443"

networks:
  default:
    external: true
    name: mynetwork
