# docker-compose -f calibre-web.yml -p calibre-web up -d
version: '2.4'
services:

  # calibre-web - Web app for browsing, reading and downloading eBooks stored in a Calibre database
  # https://github.com/janeczku/calibre-web
  # https://github.com/linuxserver/docker-calibre-web
  # Calibre Desktop: https://calibre-ebook.com/
  # Supported architectures: arm64v8, amd64
  # URL: http://localhost:8083/
  # Default admin login: Username: admin Password: admin123
  # Read: https://github.com/linuxserver/docker-calibre-web#application-setup
  calibre-web:
    image: linuxserver/calibre-web:latest # ghcr.io/linuxserver/calibre-web:latest | lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    volumes:
      - ./data_calibre-web/data:/config:rw
      - ./data_calibre-web/library:/books:rw  # add metadata.db and books from calibre desktop
    #ports:
    #  - "8083:8083/tcp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional (x64 only)
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1                   #optional
    healthcheck:
      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 8083 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 45s
    labels:
      - "traefik.enable=true"
      #- "traefik.docker.network=mynetwork"
      - "traefik.http.services.calibre-web.loadbalancer.server.port=8083"
      - "traefik.http.services.calibre-web.loadbalancer.server.scheme=http"  # when "https" then set "--serversTransport.insecureSkipVerify=true" for traefik
      # http
      - "traefik.http.routers.calibre-web-http.rule=Host(`ebooks.example.com`,`calibre-web.example.com`)"
      - "traefik.http.routers.calibre-web-http.entrypoints=web"
      - "traefik.http.routers.calibre-web-http.service=calibre-web"
      # https
      - "traefik.http.routers.calibre-web-https.tls=true"
      - "traefik.http.routers.calibre-web-https.rule=Host(`ebooks.example.com`,`calibre-web.example.com`)"
      - "traefik.http.routers.calibre-web-https.entrypoints=websecure"
      - "traefik.http.routers.calibre-web-https.service=calibre-web"
      # load middlewares for routers
      - "traefik.http.routers.calibre-web-http.middlewares=calibre-web-https"
      # http to https redirect
      - "traefik.http.middlewares.calibre-web-https.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.calibre-web-https.redirectscheme.permanent=true"
      #- "traefik.http.middlewares.calibre-web-https.redirectscheme.port=443"

networks:
  default:
    external: true
    name: mynetwork
