# docker-compose -f consul.yml up -d
version: '2.4'
services:

  consul-server0:
    image: hashicorp/consul:1.16
    container_name: consul-server0
    #restart: unless-stopped
    volumes:
     - ./config_consul/server0.json:/consul/config/server.json:ro
     - ./data_consul-server/server-0:/consul/data:rw
    ports:
      - "8500:8500/tcp" # HTTP API
      #- "8600:8600/tcp" # DNS
      #- "8600:8600/udp" # DNS
    command: "agent"
    healthcheck:
      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 8500 || exit 1"]
      #start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      #- "traefik.docker.network=mynetwork"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"
      - "traefik.http.services.consul.loadbalancer.server.scheme=http"  # when "https" then set "--serversTransport.insecureSkipVerify=true" for traefik
      # http
      - "traefik.http.routers.consul-http.rule=Host(`consul.example.com`)"
      - "traefik.http.routers.consul-http.entrypoints=web"
      - "traefik.http.routers.consul-http.service=consul"
      # https
      - "traefik.http.routers.consul-https.tls=true"
      - "traefik.http.routers.consul-https.rule=Host(`consul.example.com`)"
      - "traefik.http.routers.consul-https.entrypoints=websecure"
      - "traefik.http.routers.consul-https.service=consul"
      # load middlewares for routes
      #- "traefik.http.routers.consul-http.middlewares=consul-https"
      # http to https redirect      
      #- "traefik.http.middlewares.consul-https.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.consul-https.redirectscheme.permanent=true"
      #- "traefik.http.middlewares.consul-https.redirectscheme.port=443"
      
  consul-server1:
    image: hashicorp/consul:1.16
    container_name: consul-server1
    #restart: unless-stopped
    volumes:
     - ./config_consul/server1.json:/consul/config/server.json:ro
     - ./data_consul-server/server-1:/consul/data:rw
    #ports:
    #  - "8500:8500"
    #  - "8600:8600/tcp"
    #  - "8600:8600/udp"
    command: "agent"
    healthcheck:
      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 8500 || exit 1"]
      #start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3
    
  consul-client:
    image: hashicorp/consul:1.16
    container_name: consul-client
    #restart: unless-stopped
    volumes:
     - ./config_consul/client.json:/consul/config/client.json:ro
     - ./data_consul-server/client:/consul/data:rw
    command: "agent"

networks:
  default:
    external: true
    name: mynetwork
