# docker-compose -f geoserver.yml up -d
version: '2.4'
services:
   
  # GeoServer - server for sharing geospatial data
  # http://geoserver.org/
  # https://github.com/geoserver/geoserver
  # https://hub.docker.com/r/kartoza/geoserver + https://github.com/kartoza/docker-geoserver
  # Supported architectures: amd64
  # URL: http://localhost:8080/
  # fix permission problem before startup: "mkdir ./data_geoserver/ && chmod 777 ./data_geoserver/"
  geoserver:
    image: kartoza/geoserver:2.20.1
    container_name: geoserver
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - TIMEZONE='Europe/Berlin'
      - GEOSERVER_DATA_DIR=/opt/geoserver/data
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data/gwc
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - RESET_ADMIN_CREDENTIALS=FALSE
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
      - TOMCAT_EXTRAS=false
      #- GEOSERVER_CSRF_DISABLED=false
    ports:
      - 8080:8080/tcp
    volumes:
      - ./data_geoserver:/opt/geoserver/data:rw
    healthcheck:
      test: curl --fail -s http://127.0.0.1:8080/geoserver/web || exit 1
      #start_period: 30s
      interval: 60s
      timeout: 10s
      retries: 3

networks:
  default:
    external: true
    name: mynetwork
