# docker-compose -f gitea.yml up -d
version: '2.4'
services:

  # Git-Server: Gitea OR Forgejo
  # difference between Forgejo and Gitea: https://forgejo.org/compare/
  # Gitea: https://about.gitea.com/
  # * https://github.com/go-gitea/gitea
  # * https://docs.gitea.com/installation/install-with-docker
  # * https://docs.gitea.com/administration/config-cheat-sheet
  # Forgejo: https://forgejo.org/
  # * https://codeberg.org/forgejo/forgejo
  # * https://forgejo.org/docs/latest/admin/installation-docker/
  # * https://forgejo.org/docs/latest/admin/config-cheat-sheet/
  # Supported architectures: amd64, arm64
  gitea:
    image: gitea/gitea:1.21
    #image: codeberg.org/forgejo/forgejo:1.21
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # use GITEA__ OR FORGEJO__ !
      # Gitea
      - GITEA__DEFAULT__APP_NAME=Git
      - GITEA__time__DEFAULT_UI_LOCATION=Europe/Berlin
      - GITEA__server__DOMAIN=git.example.com
      - GITEA__server__ROOT_URL=https://git.example.com
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__DISABLE_SSH=false
      - GITEA__server__SSH_DOMAIN=git.example.com
      - GITEA__server__SSH_PORT=2222
      - GITEA__server__SSH_LISTEN_PORT=22
      - GITEA__server__DISABLE_REGISTRATION=false
      - GITEA__database__DB_TYPE=mysql  # sqlite3, mysql, postgres, mssql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=git
      - GITEA__database__USER=git
      - GITEA__database__PASSWD=passw0rd
      - GITEA__cache__ENABLED=true
      - GITEA__cache__ADAPTER=redis  # memory, redis, redis-cluster, twoqueue or memcache
      - GITEA__cache__HOST=redis://:passw0rd@gitea-cache:6379/0?pool_size=100&idle_timeout=180s
      - GITEA__cache__ITEM_TTL=24h
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__PROTOCOL=smtps # "smtp", "smtps", "smtp+starttls", "smtp+unix", "sendmail", "dummy"
      - GITEA__mailer__SMTP_ADDR=mail.example.com
      - GITEA__mailer__SMTP_PORT=465
      - GITEA__mailer__USER=git@example.com
      - GITEA__mailer__PASSWD=passw0rd
      - GITEA__mailer__FROM=git@example.com
      - GITEA__service__REGISTER_EMAIL_CONFIRM=true
      - GITEA__service__ENABLE_NOTIFY_MAIL=true
      #- GITEA__service__DISABLE_REGISTRATION=false
      - GITEA__log__LEVEL=Info # Trace, Debug, Info, Warn, Error, Critical, Fatal, None
    volumes:
      - ./data_gitea:/data:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      #- "3000:3000"
      - "2222:22"
    networks:
      - git-net
      - traefik
    depends_on:
      gitea-db:
        condition: service_healthy # service_healthy or service_started
      gitea-cache:
        condition: service_healthy # service_healthy or service_started
    healthcheck:
      test:  wget --quiet --tries=1 --spider --no-check-certificate http://127.0.0.1:3000/api/healthz || exit 1
      #start_period: 30s
      interval: 15s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.services.gitea.loadbalancer.server.scheme=http"  # when "https" then set "--serversTransport.insecureSkipVerify=true" for traefik
      # http
      - "traefik.http.routers.gitea-http.rule=Host(`git.example.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.gitea-http.entrypoints=web"
      - "traefik.http.routers.gitea-http.service=gitea"
      # https
      - "traefik.http.routers.gitea-https.tls=true"
      - "traefik.http.routers.gitea-https.rule=Host(`git.example.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.gitea-https.entrypoints=websecure"
      - "traefik.http.routers.gitea-https.service=gitea"
      # load middlewares for routers
      - "traefik.http.routers.gitea-http.middlewares=gitea-https"
      # http to https redirect
      - "traefik.http.middlewares.gitea-https.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.gitea-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.gitea-https.redirectscheme.port=443"
      # https://docs.gitea.com/administration/reverse-proxies#traefik-with-a-sub-path
      #- "traefik.http.middlewares.gitea-stripprefix.stripprefix.prefixes=/gitea"

  # https://github.com/Tob1as/docker-kubernetes-collection/blob/master/examples_docker-compose/mariadb.yml    
  gitea-db:
    image: docker.io/library/mariadb:10.11
    container_name: gitea-db
    restart: unless-stopped
    volumes:
      - ./data_gitea-db:/var/lib/mysql:rw
    environment:
      TZ: Europe/Berlin
      MARIADB_ROOT_PASSWORD: passw0rd
      MARIADB_DATABASE: git
      MARIADB_USER: git
      MARIADB_PASSWORD: passw0rd
      #MARIADB_AUTO_UPGRADE: 1
    #ports:
    #  - 127.0.0.1:3306:3306/tcp
    healthcheck:
      #test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MARIADB_ROOT_PASSWORD || exit 1
      test:  mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD || exit 1
      #start_period: 30s
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - git-net
       
  # https://github.com/Tob1as/docker-kubernetes-collection/blob/master/examples_docker-compose/redis.yml       
  gitea-cache:
    image: docker.io/library/redis:alpine
    container_name: gitea-cache
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      REDIS_PASSWORD: passw0rd
    command: ["sh", "-c", "exec redis-server --loglevel warning --requirepass $${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD","sh","-c","exec redis-cli --no-auth-warning -a $${REDIS_PASSWORD} ping"]
      #start_period: 30s
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - git-net

#  # https://docs.gitea.com/usage/actions/act-runner
#  # An extra host for the Runner is recommended. ;)
#  # * mkdir ./data_gitea-runner
#  # * docker run --entrypoint="" --rm -it gitea/act_runner:latest act_runner generate-config > ./data_gitea-runner/config.yaml
#  # or for forgejo: https://forgejo.codeberg.page/docs/latest/admin/actions/#installation-of-the-oci-image
#  gitea-runner:
#    image: gitea/act_runner:latest
#    container_name: gitea-runner
#    restart: unless-stopped
#    environment:
#      CONFIG_FILE: /config.yaml
#      GITEA_INSTANCE_URL: "https://git.example.com"
#      GITEA_RUNNER_REGISTRATION_TOKEN: "TOKEN"
#      GITEA_RUNNER_NAME: "GIT-Runner-0"
#      GITEA_RUNNER_LABELS: ""
#    volumes:
#      - ./config_gitea-runner/config.yaml:/config.yaml
#      - ./data_gitea-runner:/data:rw
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro  # when need other certs (e.g.: self-signed certificate)
#    networks:
#      - git-runner-net
#    #depends_on:
#    #  gitea:
#    #    condition: service_healthy # or service_started

networks:
  git-net:
    name: git-net
#  git-runner-net:
#    name: git-runner-net
  traefik:
    external: true
    name: mynetwork