# docker-compose -f hoppscotch.yml up -d
version: '2.4'
services:

  # Hoppscotch - Open source API development ecosystem
  # https://hoppscotch.io/
  # https://github.com/hoppscotch/hoppscotch + https://hub.docker.com/r/hoppscotch/hoppscotch
  # https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build#using-the-aio-container
  # Supported architectures: amd64, arm64
  hoppscotch:
    image: hoppscotch/hoppscotch:latest  # 2024.10.2
    container_name: hoppscotch
    restart: unless-stopped
    env_file:
      - ./envs/hoppscotch.env  # https://github.com/hoppscotch/hoppscotch/blob/main/.env.example
    #ports:
    #  - 80/tcp
    healthcheck:
      test: ["CMD", "curl", "--fail", "--insecure", "http://localhost:8080/ping"]
      #start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.hoppscotch.loadbalancer.server.port=80"
      # http
      - "traefik.http.routers.hoppscotch-http.rule=Host(`hoppscotch.example.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.hoppscotch-http.entrypoints=web"
      - "traefik.http.routers.hoppscotch-http.service=hoppscotch"
      # https
      - "traefik.http.routers.hoppscotch-https.tls=true"
      - "traefik.http.routers.hoppscotch-https.rule=Host(`hoppscotch.example.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.hoppscotch-https.entrypoints=websecure"
      - "traefik.http.routers.hoppscotch-https.service=hoppscotch"
      # load middlewares for routes
      - "traefik.http.routers.hoppscotch-http.middlewares=hoppscotch-https,hoppscotch-headers"
      - "traefik.http.routers.hoppscotch-https.middlewares=hoppscotch-headers"
      # http to https redirect      
      - "traefik.http.middlewares.hoppscotch-https.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.hoppscotch-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.hoppscotch-https.redirectscheme.port=443"
      
      # CORS https://doc.traefik.io/traefik/middlewares/http/headers/#cors-headers
      - "traefik.http.middlewares.hoppscotch-headers.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.hoppscotch-headers.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.hoppscotch-headers.headers.accesscontrolalloworiginlist=https://hoppscotch.example.com"
      - "traefik.http.middlewares.hoppscotch-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.hoppscotch-headers.headers.addvaryheader=true"
    networks:
      - hoppscotch-net
      - traefik
    depends_on:
      - hoppscotch-db
    # IMPORTANT: USE FOR FIRST RUN ! (to create/update database tables)
    #entrypoint: [ "/bin/sh", "-c", "--" ]
    #command: [ "pnpx prisma migrate deploy" ]
  
  # https://github.com/Tob1as/docker-kubernetes-collection/blob/master/examples_docker-compose/postgres.yml
  hoppscotch-db:
    image: postgres:15-alpine 
    container_name: hoppscotch-db
    restart: unless-stopped
    volumes:
      - ./data_hoppscotch-db:/var/lib/postgresql/data:rw
    environment:
      TZ: Europe/Berlin
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: hoppscotch
      POSTGRES_USER: postgres
      #PGDATA: /var/lib/postgresql/data/pgdata
    #ports:
    #  - 127.0.0.1:5432:5432/tcp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - hoppscotch-net
      
  # proxyscotch - A simple proxy server created for Hoppscotch.
  # https://github.com/hoppscotch/proxyscotch
  # https://github.com/Tob1as/docker-tools
  proxyscotch:
    image: tobi312/tools:proxyscotch  # v0.1.1  (or: hoppscotch/proxyscotch:latest)
    container_name: proxyscotch
    restart: unless-stopped
    #command:
    #  - "-host"
    #  - "0.0.0.0:9159"
    #  - "-token"
    #  - "my-token-passw0rd"
    #ports:
    #  - 9159/tcp
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.proxyscotch.loadbalancer.server.port=9159"
      # http
      - "traefik.http.routers.proxyscotch-http.rule=Host(`hoppscotch.example.com`) && PathPrefix(`/proxy`)"
      - "traefik.http.routers.proxyscotch-http.entrypoints=web"
      - "traefik.http.routers.proxyscotch-http.service=proxyscotch"
      # https
      - "traefik.http.routers.proxyscotch-https.tls=true"
      - "traefik.http.routers.proxyscotch-https.rule=Host(`hoppscotch.example.com`) && PathPrefix(`/proxy`)"
      - "traefik.http.routers.proxyscotch-https.entrypoints=websecure"
      - "traefik.http.routers.proxyscotch-https.service=proxyscotch"
      # load middlewares for routes
      - "traefik.http.routers.proxyscotch-http.middlewares=proxyscotch-https,proxyscotch-headers"
      - "traefik.http.routers.proxyscotch-https.middlewares=proxyscotch-headers"
      # http to https redirect      
      - "traefik.http.middlewares.proxyscotch-https.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.proxyscotch-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.proxyscotch-https.redirectscheme.port=443"
      
      # CORS https://doc.traefik.io/traefik/middlewares/http/headers/#cors-headers
      - "traefik.http.middlewares.proxyscotch-headers.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.proxyscotch-headers.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.proxyscotch-headers.headers.accesscontrolalloworiginlist=https://hoppscotch.example.com"
      - "traefik.http.middlewares.proxyscotch-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.proxyscotch-headers.headers.addvaryheader=true"
    networks:
      #- proxyscotch-net
      - traefik

networks:
  hoppscotch-net:
    name: hoppscotch-net
  traefik:
    external: true
    name: mynetwork
