  # docker-compose -f keycloak.yml up -d
version: '2.4'
services:

  # https://hub.docker.com/_/mariadb + https://github.com/MariaDB/mariadb-docker
  db:
    image: mariadb:10.6
    container_name: keycloak-db
    restart: unless-stopped
    volumes:
      - ./keycloak-db:/var/lib/mysql:rw
    environment:
      TZ: Europe/Berlin
      MARIADB_ROOT_PASSWORD: passw0rd
      MARIADB_DATABASE: keycloak
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: passw0rd
    #ports:
    #  - 3306/tcp
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MARIADB_ROOT_PASSWORD || exit 1
      #test:  mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD || exit 1
      interval: 60s
      timeout: 5s
      retries: 2
      #start_period: 30s

  # Keycloak - identity and access management solution
  # https://www.keycloak.org/
  # https://github.com/keycloak/keycloak
  # https://hub.docker.com/r/jboss/keycloak + https://github.com/keycloak/keycloak-containers/tree/main/server
  # Supported architectures: amd64
  # URL: http://localhost:8080/auth
  # Requirements: setup database (mariadb or other database) before start keycloak!
  keycloak:
    image: jboss/keycloak:16.1.1
    #image: quay.io/keycloak/keycloak:16.1.1
    container_name: keycloak
    environment:
      #TZ: Europe/Berlin
      DB_VENDOR: mariadb                # Supported values: h2, postgres, mysql, mariadb, oracle, mssql
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: passw0rd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: passw0rd
      #KEYCLOAK_LOGLEVEL: INFO
      #ROOT_LOGLEVEL: INFO
      #PROXY_ADDRESS_FORWARDING: "true"  # use behind proxy !
      #KEYCLOAK_FRONTEND_URL: "https://auth.example.com"
      #JAVA_OPTS: "-server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true"
      #JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.docker=enabled -Dkeycloak.profile.feature.recovery_codes=enabled"
      #KEYCLOAK_STATISTICS: all          # metrics
      #KEYCLOAK_WELCOME_THEME: ""
      #KEYCLOAK_DEFAULT_THEME: ""
      #X509_CA_BUNDLE: "/tmp/ca/*.crt"   # import automatically CA certs from this folder in truststore.jks
      # check truststore: keytool -list -v -keystore ${JBOSS_HOME}/standalone/configuration/keystores/truststore.jks -storepass $(cat $JBOSS_HOME/bin/.jbossclirc | grep truststore_password | sed 's/[^=]*=//')
    restart: unless-stopped
    #volumes:
      #- ./keycloak-config/themes/my-theme:/opt/jboss/keycloak/themes/my-theme:ro
      #- ./keycloak-config/customprovider:/opt/jboss/keycloak/standalone/deployments:ro
      #- ./keycloak-config/ca-certs:/tmp/ca:ro
    ports:
      #- 8080/tcp
      - 8080:8080/tcp
    healthcheck:
      test:  curl -fL  http://localhost:8080/auth/realms/master || exit 1
      #start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3
    depends_on:
      - db
