# docker-compose -f mariadb.yml up -d
version: '2.4'
services:

  # MariaDB - relational database (SQL), forked from MySQL
  # https://mariadb.org/
  # https://hub.docker.com/_/mariadb
  # https://github.com/MariaDB/mariadb-docker
  # https://github.com/Tob1asDocker/rpi-mariadb/
  # Optional: additional user without admin permission
  # * with init script (init-user-db.sh): https://github.com/docker-library/docs/tree/master/mariadb#initializing-a-fresh-instance
  # * with docker command when container running: docker exec -it mariadb sh -c 'mysql -u root --password=$MARIADB_ROOT_PASSWORD'
  #   CREATE USER IF NOT EXISTS 'user_name'@'%' IDENTIFIED BY 'user_password' WITH MAX_USER_CONNECTIONS 0;
  #   CREATE DATABASE IF NOT EXISTS database_name CHARACTER SET='utf8' COLLATE='utf8_general_ci';
  #   GRANT ALL PRIVILEGES ON database_name.* TO 'user_name'@'%';
  #   FLUSH PRIVILEGES;
  mariadb:
    image: mariadb:10.11                      # Supported architectures: amd64, arm64v8
    # image: tobi312/rpi-mariadb:10.11-alpine # Supported architectures: arm32v7 (RaspberryPi)
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./mariadb-data:/var/lib/mysql:rw
      #- ./mariadb-init/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Europe/Berlin
      MARIADB_ROOT_PASSWORD: passw0rd
      #MARIADB_DATABASE: db
      #MARIADB_USER: user
      #MARIADB_PASSWORD: passw0rd
    #  MARIADB_EXPORTER_PASSWORD: passw0rd
    #entrypoint:
    #  sh -c "
    #    echo \"SET GLOBAL time_zone = '$$TZ'; SET time_zone = '$$TZ'; SELECT CURRENT_TIME; CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY '$$MARIADB_EXPORTER_PASSWORD' WITH MAX_USER_CONNECTIONS 3; GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%'; \" > /docker-entrypoint-initdb.d/init.sql;
    #    /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #  "
    ports:
      - 3306:3306/tcp
      #- 127.0.0.1:3306:3306/tcp # use this and comment out the other, if you want connect only from localhost
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MARIADB_ROOT_PASSWORD || exit 1
      #test:  mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
      #start_period: 30s
