# docker-compose -f memcached.yml up -d
version: '2.4'
services:
  
  # Memcached - memory object caching system
  # https://memcached.org/
  # https://github.com/memcached/memcached
  # https://hub.docker.com/_/memcached + https://github.com/docker-library/memcached
  # Supported architectures: arm32v5, arm32v6, arm32v7, arm64v8, amd64, ...
  memcached:
    image: memcached:latest
    container_name: memcached
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
    #ports:    # Do NOT open port external (without password)!
    #  - 127.0.0.1:11211:11211/tcp
    #entrypoint: memcached -m 256
    healthcheck:
      test: ["CMD","sh","-c","exec memcached --version"]
      #start_period: 30s
      interval: 60s
      timeout: 10s
      retries: 3

  # https://github.com/prometheus/memcached_exporter
  # Supported architectures: arm32v7, arm64v8, amd64
  memcached-exporter:
    image: prom/memcached-exporter:latest # quay.io/prometheus/memcached-exporter:latest
    container_name: memcached-exporter
    restart: unless-stopped
    ports:
      - 127.0.0.1:9150:9150/tcp
    command:
      - "--memcached.address=memcached:11211"
      #- "--web.listen-address=:9150"
      #- "--web.telemetry-path=/metrics"
    depends_on:
      - memcached

networks:
  default:
    external: true
    name: mynetwork
