# docker-compose -f minio.yml up -d
version: '2.4'
services:

  # MinIO - Object Storage compatible with S3
  # https://min.io/
  # https://github.com/minio/minio
  # https://hub.docker.com/r/minio/minio
  # https://github.com/Tob1asDocker/minio
  # URL: http://localhost:9001/
  # fix permission problem before startup, when use user/group settings: "mkdir ./minio-data && chmod 777 ./minio-data"
  minio:
    image: minio/minio:latest     # Supported architectures: amd64, arm64 
    #image: tobi312/minio:latest  # Supported architectures: amd64, arm64, arm32 (RaspberryPi) (based on AlpineLinux)
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000/tcp" # MinIO Buckets API
      - "9001:9001/tcp" # MinIO Console
    volumes:
      #- minio-data:/data:rw
      - ./minio-data:/data:rw
      #- ./ssl/ssl.crt:/root/.minio/certs/public.crt:ro  # works only with root user and set URLs (and Port)
      #- ./ssl/ssl.key:/root/.minio/certs/private.key:ro # (https://github.com/Tob1asDocker/minio/issues/1#issuecomment-1003127867)
      #- ./ssl/ca.crt:/root/.minio/certs/CAs/ca.crt:ro
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      # user/group in container instead root
      MINIO_USERNAME: minio
      MINIO_GROUPNAME: minio
      MINIO_UID: 1000
      MINIO_GID: 1000
      # use for MinIO Console behind a load balancer, proxy or k8s ingress
      #MINIO_SERVER_URL: "https://minio.example.net"
      #MINIO_BROWSER_REDIRECT_URL: "https://console.minio.example.net"
    command:  ["server", "--address", ":9000", "--console-address", ":9001", "/data"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000/minio/health/live"]
      #test: ["CMD", "curl", "--fail", "--insecure", "https://localhost:9000/minio/health/live"] # when use minio ssl
      #start_period: 30s
      interval: 60s
      timeout: 10s
      retries: 3
    #labels:
    #  - "traefik.enable=true"
    #  # MINIO-Console
    #  - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
    #  - "traefik.http.services.minio-console.loadbalancer.server.scheme=http"  # when "https" then set "--serversTransport.insecureSkipVerify=true" for traefik
    #  # http
    #  - "traefik.http.routers.minio-console-http.rule=Host(`minio-console.example.net`)"
    #  - "traefik.http.routers.minio-console-http.entrypoints=web"
    #  - "traefik.http.routers.minio-console-http.service=minio-console"
    #  # https
    #  - "traefik.http.routers.minio-console-https.tls=true"
    #  - "traefik.http.routers.minio-console-https.rule=Host(`minio-console.example.net`)"
    #  - "traefik.http.routers.minio-console-https.entrypoints=websecure"
    #  - "traefik.http.routers.minio-console-https.service=minio-console"
    #  # http to https redirect      
    #  - "traefik.http.routers.minio-console-http.middlewares=minio-console-https"
    #  - "traefik.http.middlewares.minio-console-https.redirectscheme.scheme=https"
    #  #- "traefik.http.middlewares.minio-console-https.redirectscheme.permanent=true"
    #  #- "traefik.http.middlewares.minio-console-https.redirectscheme.port=443"
    #  # MINIO API
    #  - "traefik.http.services.minio.loadbalancer.server.port=9000"
    #  - "traefik.http.services.minio.loadbalancer.server.scheme=http"          # when "https" then set "--serversTransport.insecureSkipVerify=true" for traefik
    #  # http
    #  - "traefik.http.routers.minio-http.rule=Host(`minio.example.net`)"
    #  - "traefik.http.routers.minio-http.entrypoints=web"
    #  - "traefik.http.routers.minio-http.service=minio"
    #  # https
    #  - "traefik.http.routers.minio-https.tls=true"
    #  - "traefik.http.routers.minio-https.rule=Host(`minio.example.net`)"
    #  - "traefik.http.routers.minio-https.entrypoints=websecure"
    #  - "traefik.http.routers.minio-https.service=minio"
    #  # http to https redirect      
    #  - "traefik.http.routers.minio-http.middlewares=minio-https"
    #  - "traefik.http.middlewares.minio-https.redirectscheme.scheme=https"
    #  #- "traefik.http.middlewares.minio-https.redirectscheme.permanent=true"
    #  #- "traefik.http.middlewares.minio-https.redirectscheme.port=443"

#volumes:
#  minio-data:
