# docker-compose -f mongo.yml -p mongo up -d
version: '2.4'
services:
  
  # MongoDB - document-oriented database (NoSQL)
  # https://www.mongodb.com/
  # https://github.com/mongodb/mongo
  # https://hub.docker.com/_/mongo + https://github.com/docker-library/mongo
  # Supported architectures: arm64v8, amd64, ...
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./data_mongo:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
    ports:
      - 127.0.0.1:27017:27017/tcp
    healthcheck:
      test:  mongo -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval db.adminCommand\(\"ping\"\) || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      #start_period: 30s

  # https://github.com/percona/mongodb_exporter
  # Supported architectures: arm64v8, amd64
  mongo-exporter:
    image: percona/mongodb_exporter:0.39 # or: 0.20 ?
    container_name: mongo-exporter
    restart: unless-stopped
    #ports:
    #  - 127.0.0.1:9216:9216/tcp
    command:
      - "--mongodb.uri=mongodb://admin:passw0rd@mongo:27017"
      #- "--web.listen-address=:9216"
      #- "--web.telemetry-path=/metrics"
    depends_on:
      - mongo

  # mongo-express - Web-based MongoDB admin interface
  # https://github.com/mongo-express/mongo-express
  # https://hub.docker.com/_/mongo-express + https://github.com/mongo-express/mongo-express-docker
  # Supported architectures: arm64v8, amd64
  # URL: http://localhost:8081/
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    environment:
      # https://github.com/mongo-express/mongo-express-docker#configuration
      # https://github.com/mongo-express/mongo-express#usage-docker
      #ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017"  # if mongo use auth, then comment in and use "ME_CONFIG_MONGODB_URL with auth cred."
      ME_CONFIG_MONGODB_URL: "mongodb://admin:passw0rd@mongo:27017"
      ME_CONFIG_OPTIONS_EDITORTHEME: "default"
      #ME_CONFIG_REQUEST_SIZE: "100kb"
      #ME_CONFIG_SITE_BASEURL: "/mongo-express/"
      #ME_CONFIG_SITE_SSL_ENABLED: "false"
      #ME_CONFIG_SITE_SSL_CRT_PATH: ""
      #ME_CONFIG_SITE_SSL_KEY_PATH: ""
      #ME_CONFIG_MONGODB_SSLVALIDATE: "true"
      #ME_CONFIG_OPTIONS_READONLY: "false"
      #ME_CONFIG_OPTIONS_NO_DELETE: "false"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "passw0rd"
      #ME_CONFIG_SITE_COOKIESECRET: "cookiesecret"
      #ME_CONFIG_SITE_SESSIONSECRET: "sessionsecret"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      #ME_CONFIG_MONGODB_AUTH_DATABASE: "db"       # only needed if ME_CONFIG_MONGODB_ENABLE_ADMIN is "false"
      #ME_CONFIG_MONGODB_AUTH_USERNAME: "admin"    # only needed if ME_CONFIG_MONGODB_ENABLE_ADMIN is "false"
      #ME_CONFIG_MONGODB_AUTH_PASSWORD: "passw0rd" # only needed if ME_CONFIG_MONGODB_ENABLE_ADMIN is "false"
    #ports:
    #  - 8081:8081/tcp
    healthcheck:
      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 8081 || exit 1"]
      #start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      #- "traefik.docker.network=mynetwork"
      - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"
      #- "traefik.http.services.mongo-express.loadbalancer.server.scheme=http"  # when "https" then set "--serversTransport.insecureSkipVerify=true" for traefik
      # http
      - "traefik.http.routers.mongo-express-http.rule=Host(`mongo-express.example.com`)"
      - "traefik.http.routers.mongo-express-http.entrypoints=web"
      - "traefik.http.routers.mongo-express-http.service=mongo-express"
      # https
      - "traefik.http.routers.mongo-express-https.tls=true"
      - "traefik.http.routers.mongo-express-https.rule=Host(`mongo-express.example.com`)"
      - "traefik.http.routers.mongo-express-https.entrypoints=websecure"
      - "traefik.http.routers.mongo-express-https.service=mongo-express"
      # load middlewares for routes
      - "traefik.http.routers.mongo-express-http.middlewares=mongo-express-https"
      # http to https redirect      
      - "traefik.http.middlewares.mongo-express-https.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.mongo-express-https.redirectscheme.permanent=true"
      #- "traefik.http.middlewares.mongo-express-https.redirectscheme.port=443"

#  # https://github.com/SamuelTallet/MongoDB-PHP-GUI
#  # Supported architectures: arm32v7, arm64v8, amd64
#  mongo-php-gui:
#    image: samueltallet/mongodb-php-gui:latest
#    container_name: mongo-php-gui
#    restart: unless-stopped
#    #ports:
#    #  - 5000:5000/tcp
#    healthcheck:
#      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 5000 || exit 1"]
#      #start_period: 60s
#      interval: 60s
#      timeout: 5s
#      retries: 3
#    #depends_on:
#    #  - mongo
#    labels:
#      - "traefik.enable=true"
#      #- "traefik.docker.network=mynetwork"
#      - "traefik.http.services.mongo-php-gui.loadbalancer.server.port=5000"
#      - "traefik.http.services.mongo-php-gui.loadbalancer.server.scheme=http"
#      # http
#      - "traefik.http.routers.mongo-php-gui-http.rule=Host(`mongo-php-gui.example.com`)"
#      - "traefik.http.routers.mongo-php-gui-http.entrypoints=web"
#      - "traefik.http.routers.mongo-php-gui-http.service=mongo-php-gui"
#      # https
#      - "traefik.http.routers.mongo-php-gui-https.tls=true"
#      - "traefik.http.routers.mongo-php-gui-https.rule=Host(`mongo-php-gui.example.com`)"
#      - "traefik.http.routers.mongo-php-gui-https.entrypoints=websecure"
#      - "traefik.http.routers.mongo-php-gui-https.service=mongo-php-gui"
#      # load middlewares for routes
#      - "traefik.http.routers.mongo-php-gui-http.middlewares=mongo-php-gui-https"
#      # http to https redirect      
#      - "traefik.http.middlewares.mongo-php-gui-https.redirectscheme.scheme=https"
#      #- "traefik.http.middlewares.mongo-php-gui-https.redirectscheme.permanent=true"
#      #- "traefik.http.middlewares.mongo-php-gui-https.redirectscheme.port=443"
      
#  # https://github.com/arunbandari/mongo-gui
#  # Supported architectures: amd64
#  mongo-gui:
#    image: ugleiton/mongo-gui:latest
#    build:
#      context: https://github.com/arunbandari/mongo-gui.git#:/
#      dockerfile: Dockerfile
#    container_name: mongo-gui
#    restart: unless-stopped
#    environment:
#      - MONGO_URL=mongodb://admin:passw0rd@mongo:27017
#      - OPENAI_API_KEY=YOUR_API_KEY_HERE
#      #- USERNAME=admin
#      #- PASSWORD="passw0rd"
#    #ports:
#    #  - 4321:4321/tcp
#    depends_on:
#      - mongo
#    labels:
#      - "traefik.enable=true"
#      #- "traefik.docker.network=mynetwork"
#      - "traefik.http.services.mongo-gui.loadbalancer.server.port=4321"
#      - "traefik.http.services.mongo-gui.loadbalancer.server.scheme=http"
#      # http
#      - "traefik.http.routers.mongo-gui-http.rule=Host(`mongo-gui.example.com`)"
#      - "traefik.http.routers.mongo-gui-http.entrypoints=web"
#      - "traefik.http.routers.mongo-gui-http.service=mongo-gui"
#      # https
#      - "traefik.http.routers.mongo-gui-https.tls=true"
#      - "traefik.http.routers.mongo-gui-https.rule=Host(`mongo-gui.example.com`)"
#      - "traefik.http.routers.mongo-gui-https.entrypoints=websecure"
#      - "traefik.http.routers.mongo-gui-https.service=mongo-gui"
#      # load middlewares for routes
#      - "traefik.http.routers.mongo-gui-http.middlewares=mongo-gui-https,mongo-gui-auth"
#      - "traefik.http.routers.mongo-gui-https.middlewares=mongo-gui-auth"
#      # http to https redirect      
#      - "traefik.http.middlewares.mongo-gui-https.redirectscheme.scheme=https"
#      #- "traefik.http.middlewares.mongo-gui-https.redirectscheme.permanent=true"
#      #- "traefik.http.middlewares.mongo-gui-https.redirectscheme.port=443"
#      # auth (You may need to escape any $ with another $.) (docker run --rm tobi312/tools:htpasswd -bn redis passw0rd)
#      - "traefik.http.middlewares.mongo-gui-auth.basicauth.users=admin:$$apr1$$S19kucpw$$YssXd6k23MIOOEn6hLVMf."

networks:
  default:
    external: true
    name: mynetwork
