# docker-compose -f mongo.yml up -d
version: '2.4'
services:
  
  # MongoDB - document-oriented database (NoSQL)
  # https://www.mongodb.com/
  # https://github.com/mongodb/mongo
  # https://hub.docker.com/_/mongo + https://github.com/docker-library/mongo
  # Supported architectures: arm64v8, amd64, ...
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./mongo-data:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
    ports:
      - 27017:27017/tcp
      #- 127.0.0.1:27017:27017/tcp # use this and comment out the other, if you want connect only from localhost
    healthcheck:
      test:  mongo -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval db.adminCommand\(\"ping\"\) || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      #start_period: 30s
