# docker-compose -f mosquitto.yml up -d
version: '2.4'
services:

  # Eclipse Mosquitto - MQTT Broker
  # https://mosquitto.org/
  # https://hub.docker.com/_/eclipse-mosquitto + https://github.com/eclipse/mosquitto
  # Docs: https://mosquitto.org/man/mosquitto-conf-5.html
  # Config: https://github.com/eclipse/mosquitto/blob/master/mosquitto.conf
  # ACL example: https://github.com/eclipse/mosquitto/blob/master/aclfile.example
  # Dockerfile: https://github.com/eclipse/mosquitto/blob/master/docker/2.0-openssl/
  # fix permission: chmod 0700 ./config_mosquitto/mosquitto.acl && chmod 0700 ./config_mosquitto/mosquitto.passwd
  # Passwd: "mosquitto_passwd -c -b /mosquitto/config/mosquitto.passwd admin passw0rd"
  mosquitto:
    image: eclipse-mosquitto:2.0.18-openssl
    container_name: mosquitto
    #hostname: mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883/tcp'    # MQTT
      - '8883:8883/tcp'    # MQTTS
    #  - '9001:8080/tcp'    # ws
    #  - '9002:9002/tcp'    # wss
    volumes:
      - ./config_mosquitto:/mosquitto/config:rw
      - ./data_mosquitto:/mosquitto/data:rw
      #- ./ssl:/mosquitto/ssl:ro
      - ./ssl/ca.crt:/mosquitto/ssl/cacerts.pem:ro
      - ./ssl/ssl.crt:/mosquitto/ssl//cert.pem:ro
      - ./ssl/ssl.key:/mosquitto/ssl/key.pem:ro
      #- ./log_mosquitto:/mosquitto/log:rw  # default to stdout
    #command: ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
    #command: [ "/usr/sbin/mosquitto", "-c", "/mosquitto-no-auth.conf" ]
    healthcheck:
      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 1883 || exit 1"]
      #start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      # TCP MQTT
      - "traefik.tcp.services.mosquitto-mqtt.loadbalancer.server.port=1883"
      - "traefik.tcp.routers.mosquitto-mqtt.service=mosquitto-mqtt"
      - "traefik.tcp.routers.mosquitto-mqtt.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mosquitto-mqtt.entrypoints=mqtt"
      # TCP MQTTS
      - "traefik.tcp.services.mosquitto-mqtts.loadbalancer.server.port=8883"
      - "traefik.tcp.routers.mosquitto-mqtts.service=mosquitto-mqtts"
      - "traefik.tcp.routers.mosquitto-mqtts.rule=HostSNI(`*`)"
      #- "traefik.tcp.routers.mosquitto-mqtts.rule=HostSNI(`mosquitto.example.com`)"
      - "traefik.tcp.routers.mosquitto-mqtts.entrypoints=mqtts"
      - "traefik.tcp.routers.mosquitto-mqtts.tls=true"
      - "traefik.tcp.routers.mosquitto-mqtts.tls.passthrough=true"
      # WebSocket Secure (wss) - wss://mosquitto.example.com on port 443
      - "traefik.http.services.mosquitto-wss.loadbalancer.server.port=8080"  # ws port (default: 8080)
      - "traefik.http.routers.mosquitto-wss.tls=true"
      - "traefik.http.routers.mosquitto-wss.rule=Host(`mosquitto.example.com`)"
      - "traefik.http.routers.mosquitto-wss.entrypoints=websecure"
      - "traefik.http.routers.mosquitto-wss.service=mosquitto-wss"
      - "traefik.http.routers.mosquitto-wss.middlewares=sslheader@docker"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      # WebSockert (ws) - ws://mosquitto.example.com on port 8080/9001
      #- "traefik.tcp.services.mosquitto-ws.loadbalancer.server.port=8080"  # ws port
      #- "traefik.tcp.routers.mosquitto-ws.service=mosquitto-ws"     
      #- "traefik.tcp.routers.mosquitto-ws.entrypoints=mqtt-ws"
      #- "traefik.tcp.routers.mosquitto-ws.tls=false"
      #- "traefik.tcp.routers.mosquitto-ws.rule=HostSNI(`*`)"

networks:
  default:
    external: true
    name: mynetwork
