# docker-compose -f mqtt-forwarder.yml -p mqtt-forwarder up -d
version: '2.4'
services:

  # mqtt-forwarder - Simple MQTT message forwarder to forward messages from one MQTT broker to another MQTT broker 
  # https://git.ypbind.de/cgit/mqtt-forwarder/
  # https://github.com/Tob1as/docker-tools/blob/main/mqtt-forwarder.scratch.Dockerfile
  # Run before start (and edit config): mkdir ./config_mqtt-forwarder && wget https://git.ypbind.de/cgit/mqtt-forwarder/plain/example/config.ini -O ./config_mqtt-forwarder/config.ini   
  mqtt-forwarder:
    image: tobi312/tools:mqtt-forwarder
    build:
      context: https://github.com/Tob1as/docker-tools/raw/main/mqtt-forwarder.scratch.Dockerfile
      dockerfile: mqtt-forwarder.scratch.Dockerfile
    container_name: mqtt-forwarder
    restart: unless-stopped
    volumes:
      - ./config_mqtt-forwarder/config.ini:/etc/mqtt-forwarder/config.ini:ro
      #- /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    #command:
    #  - "--config=/etc/mqtt-forwarder/config.ini"
    #depends_on:
    #  - mosquitto
    #  - vernemq
    #  - rabbitmq

  # or alternatively use the bridge mode of VerneMQ or Mosquitto ;-)

networks:
  default:
    external: true
    name: mynetwork