# docker-compose -f nginx.yml up -d
version: '2.4'
services:
  
  # NGINX - web server, proxy server, load balancer and more
  # https://nginx.org/
  # https://github.com/nginx/nginx
  # https://hub.docker.com/_/nginx + https://github.com/nginxinc/docker-nginx
  # Supported architectures: arm32v6, arm32v7, arm64v8, amd64, ...
  # URL: http://localhost/ + https://localhost/
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # example: https://github.com/Tob1asDocker/rpi-nginx/blob/master/default.conf
      - ./nginx/html:/var/www/html:rw
      - ./ssl:/etc/nginx/ssl:ro
    healthcheck:
      test:  wget --quiet --tries=1 --spider http://localhost:80/nginx_status || exit 1
      #test:  wget --quiet --tries=1 --spider --no-check-certificate  https://localhost:443/nginx_status || exit 1
      #start_period: 30s
      interval: 60s
      timeout: 3s
      retries: 3
