# docker-compose -f openssh-server.yml -p openssh-server up -d
version: '2.4'
services:

  # https://www.openssh.com/
  # https://github.com/linuxserver/docker-openssh-server + https://hub.docker.com/r/linuxserver/openssh-server
  # Supported architectures: amd64, arm64v8
  # create SSH-Public+Private-Key: ssh-keygen -t rsa -b 4096 -C "user@host" -f ./openssh-server_id_rsa -N '' -q
  openssh-server:
    #image: ghcr.io/linuxserver/openssh-server:latest
    image: linuxserver/openssh-server:latest
    container_name: openssh-server
    restart: unless-stopped
    hostname: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      #- PUBLIC_KEY=ssh-rsa AAAA*******== user@host
      #- PUBLIC_KEY_FILE=/path/to/file
      #- PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_NAME=sshuser
      - USER_PASSWORD=passw0rd
      #- USER_PASSWORD_FILE=/path/to/file
    volumes:
      #- ./config_openssh-server/sshd_portforwarding.sh:/custom-cont-init.d/10-sshd_portforwarding.sh:ro  # https://raw.githubusercontent.com/Tob1as/docker-kubernetes-collection/refs/heads/master/examples_docker-compose/config_openssh-server/sshd_portforwarding.sh
      - ./data_openssh-server:/config:rw
    ports:
      - 2222:2222/tcp
    #healthcheck:
    #  test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 2222 || exit 1"]
    #  #start_period: 30s
    #  interval: 60s
    #  timeout: 5s
    #  retries: 3
      
networks:
  default:
    external: true
    name: mynetwork