# docker-compose -f pgadmin.yml up -d
version: '2.4'
services:
   
  # pgAdmin - graphical management tool for PostgreSQL and derivative relational databases
  # https://www.pgadmin.org/
  # https://github.com/postgres/pgadmin4
  # https://hub.docker.com/r/dpage/pgadmin4
  # https://github.com/Tob1asDocker/tools#pgadmin4
  # URL: http://localhost:5050/pgadmin
  # fix permission problem before startup: "mkdir ./pgadmin-data && chmod 777 ./pgadmin-data"
  pgadmin:
    image: dpage/pgadmin4:latest    # Supported architectures: amd64, arm64
    #image: tobi312/tools:pgadmin4  # Supported architectures: amd64, arm64, arm32v7 (RaspberryPi)
    container_name: pgadmin4
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin:rw
    environment:
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5050
      - SCRIPT_NAME=/pgadmin
      - PGADMIN_DEFAULT_EMAIL=admin@email.local
      - PGADMIN_DEFAULT_PASSWORD=passw0rd
      # INFO: the PGADMIN_CONFIG_ prefix to any variable name from config.py
      #- PGADMIN_CONFIG_LOGIN_BANNER="\"pgAdmin4 ;-)\""
      #- PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    restart: unless-stopped
    ports:
      - 5050:5050/tcp
    healthcheck:
      test:  wget --quiet --tries=1 --spider --no-check-certificate http://localhost:5050/pgadmin/misc/ping || exit 1
      #start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3
