# docker-compose -f redis.yml up -d
version: '2.4'
services:
  
  # Redis - in-memory data structure store, used as a database, cache, and message broker
  # https://redis.io/
  # https://github.com/redis/redis
  # https://hub.docker.com/_/redis + https://github.com/docker-library/redis
  # Supported architectures: arm32v5, arm32v6, arm32v7, arm64v8, amd64, ...
  # https://github.com/docker-library/redis/issues/261#issuecomment-754896333
  # https://github.com/docker-library/redis/issues/46
  # fix permission problem before startup: "mkdir ./redis-data/ && chmod 777 ./redis-data/"
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
    #  REDIS_PASSWORD: passw0rd
    #command: ["sh", "-c", "exec redis-server --appendonly yes --save 20 1 --loglevel warning --requirepass $${REDIS_PASSWORD}"]
    command: ["sh", "-c", "exec redis-server --appendonly yes --save 20 1 --loglevel warning"]
    volumes:
      - ./redis-data:/data:rw
    #ports:    # Do NOT open port external (without password)! <https://redis.io/topics/acl>
    #  - 127.0.0.1:6379:6379/tcp
    healthcheck:
      #test: ["CMD","sh","-c","exec redis-cli --no-auth-warning -a $${REDIS_PASSWORD} ping"]
      test: ["CMD","sh","-c","exec redis-cli ping"]
      #start_period: 30s
      interval: 60s
      timeout: 10s
      retries: 3

#  # P3X Redis UI
#  # https://hub.docker.com/r/patrikx3/p3x-redis-ui + https://github.com/patrikx3/redis-ui
#  # Supported architectures: amd64
#  redis-ui:
#    image: patrikx3/p3x-redis-ui:latest
#    container_name: redis-ui
#    restart: unless-stopped
#    volumes:
#      - ./redis-ui-data:/settings:rw
#      #- ./redis-ui-data/.p3xrs-conns.json:/settings/.p3xrs-conns.json:rw  # https://github.com/patrikx3/redis-ui/blob/master/k8s/manifests/configmap.yaml
#    ports:
#      - 7843:7843/tcp