# docker-compose -f seafile-pro.yml up -d

# fork of https://manual.seafile.com/docker/pro-edition/deploy_seafile_pro_with_docker/ ...
# ... and change mount folder and add healtcheck!

version: '2.4'
services:

  # https://hub.docker.com/_/mariadb
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd    # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
      #- MARIADB_AUTO_UPGRADE=true
    volumes:
      - ./seafile-db:/var/lib/mysql:rw  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      #start_period: 30s

  # https://hub.docker.com/_/memcached
  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
    healthcheck:
      test: ["CMD","sh","-c","exec memcached --version"]
      #start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 3

  # https://hub.docker.com/_/elasticsearch
  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: seafile-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - ./seafile-elasticsearch:/usr/share/elasticsearch/data:rw  # Requested, specifies the path to Elasticsearch data persistent store.
    networks:
      - seafile-net
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail -XGET 'localhost:9200/_cluster/health?pretty' || exit 1"]
        #start_period: 30s
        interval: 60s
        timeout: 10s
        retries: 3

  # Seafile - file sync and share solution
  # https://www.seafile.com/ & https://github.com/haiwen/seafile
  # https://manual.seafile.com/docker/pro-edition/deploy_seafile_pro_with_docker/
  # https://docker.seafile.top/harbor/projects/4/repositories/seafile-pro-mc?publicAndNotLogged=yes
  # https://manual.seafile.com/config/seahub_settings_py/
  # https://github.com/haiwen/seafile/issues/2118#issuecomment-523688712 (CSRF_TRUSTED_ORIGINS = ['seafile.example.com:23456'])
  # https://forum.seafile.com/t/check-status-of-seafile-server/3720/6        
  seafile:
    image: docker.seafile.top/seafileltd/seafile-pro-mc:latest # 10.x
    container_name: seafile
    ports:
      - "80:80/tcp"
      - "443:443/tcp"  # If https is enabled, cancel the comment.
    volumes:
      - ./seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=passw0rd                     # Requested, the value shuold be root's password of MySQL service.
      #- TIME_ZONE=Europe/Berlin                     # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=me@example.com          # Specifies Seafile admin user, default is 'me@example.com'
      - SEAFILE_ADMIN_PASSWORD=passw0rd             # Specifies Seafile admin password, default is 'asecret'
      - SEAFILE_SERVER_LETSENCRYPT=false            # Whether to use https or not
      - SEAFILE_SERVER_HOSTNAME=seafile.example.com # Specifies your host name if https is enabled
      #- NON_ROOT=true
    depends_on:
      - db
      - memcached
      - elasticsearch
      # optional:
      #- av
      #- oods
    networks:
      - seafile-net
    healthcheck:
      test:  ["CMD-SHELL", "[ \"$$(curl -Ss 'http://localhost:80/api2/ping/')\" = '\"pong\"' ] || exit 1"]
      #test:  ["CMD-SHELL", "[ \"$$(curl -Ssk 'https://localhost:443/api2/ping/')\" = '\"pong\"' ] || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
      #start_period: 30s

## optional begin (need more settings, see docu)

#  # https://manual.seafile.com/docker/pro-edition/deploy_clamav_with_docker/
#  av:
#    image: mkodockx/docker-clamav:alpine
#    container_name: seafile-clamav
#    networks:
#      - seafile-net
#    healthcheck:
#      test: ["CMD", "./check.sh"]
#      interval: 60s
#      retries: 3
#      start_period: 120s

#  # https://manual.seafile.com/docker/pro-edition/deploy_onlyoffice_with_docker/    
#  oods:
#    image: onlyoffice/documentserver:latest
#    container_name: seafile-oods
#    volumes:
#      - ./seafile-oods/logs:/var/log/onlyoffice
#      - ./seafile-oods/data:/var/www/onlyoffice/Data
#      - ./seafile-oods/lib:/var/lib/onlyoffice
#      - ./seafile-oods/local-production-linux.json:/etc/onlyoffice/documentserver/local-production-linux.json
#    networks:
#      - seafile-net
#    environment:
#      - JWT_ENABLED=true
#      - JWT_SECRET=                    # openssl rand -base64 25 | tr -d '\ n'
#      - ONLYOFFICE_HTTPS_HSTS_ENABLED=false
#      - SSL_VERIFY_CLIENT=false
#      #- USE_UNAUTHORIZED_STORAGE=true # https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/96
#    healthcheck:
#      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 80 || exit 1"]
#      interval: 60s
#      timeout: 5s
#      retries: 3
#      #start_period: 30s

## optional end

networks:
  seafile-net:
