# docker-compose -f teamspeak.yml up -d
version: '2.4'
services:

  # Teamspeak - voice communication (free for 32 users)
  # https://www.teamspeak.com/
  # https://hub.docker.com/_/teamspeak
  # https://github.com/TeamSpeak-Systems/teamspeak-linux-docker-images
  # https://support.teamspeak.com/hc/en-us/articles/360002712257-Which-ports-does-the-TeamSpeak-3-server-use-
  # Supported architectures: amd64
  # Requirements: use sqlite or setup MariaDB before start teamspeak!
  # Admin-Token see in logs after start: docker logs -f teamspeak
  teamspeak:
    image: teamspeak:latest   # 3.13.6
    container_name: teamspeak
    restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 10011:10011/tcp
      - 30033:30033/tcp
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_sqlite3            # for MariaDB set to: ts3db_mariadb 
      TS3SERVER_DB_SQLCREATEPATH: create_sqlite     # for MariaDB set to: create_mariadb
      #TS3SERVER_DB_HOST: mariadb                   # for MariaDB comment in (delete # in front of line)
      #TS3SERVER_DB_PORT: 3306                      # for MariaDB comment in
      #TS3SERVER_DB_NAME: teamspeak                 # for MariaDB comment in
      #TS3SERVER_DB_USER: teamspeak                 # for MariaDB comment in
      #TS3SERVER_DB_PASSWORD: passw0rd              # for MariaDB comment in
      #TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - ./data_teamspeak:/var/ts3server:rw
    healthcheck:
      #test:  ["CMD-SHELL", "[ \"$$(wget -qO- localhost:30033 2>&1)\" = \"wget: error getting response: Connection reset by peer\" ] || exit 1"]
      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 10011 || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
      #start_period: 30s
    #labels:
    #  - "traefik.enable=true"
    #  #- "traefik.docker.network=mynetwork"
    #  # UDP 9987
    #  - "traefik.udp.services.teamspeak-udp.loadbalancer.server.port=9987"
    #  - "traefik.udp.routers.teamspeak-udp.service=teamspeak-udp"
    #  - "traefik.udp.routers.teamspeak-udp.entrypoints=ts-udp"
    #  # TCP 10011 serverquery
    #  - "traefik.tcp.services.teamspeak-tcp-sq.loadbalancer.server.port=10011"
    #  - "traefik.tcp.routers.teamspeak-tcp-sq.service=teamspeak-tcp-sq"
    #  - "traefik.tcp.routers.teamspeak-tcp-sq.rule=HostSNI(`*`)"
    #  - "traefik.tcp.routers.teamspeak-tcp-sq.entrypoints=ts-tcp-sq"
    #  # TCP 30033 filetransfer
    #  - "traefik.tcp.services.teamspeak-tcp-ft.loadbalancer.server.port=10011"
    #  - "traefik.tcp.routers.teamspeak-tcp-ft.service=teamspeak-tcp-ft"
    #  - "traefik.tcp.routers.teamspeak-tcp-ft.rule=HostSNI(`*`)"
    #  - "traefik.tcp.routers.teamspeak-tcp-ft.entrypoints=ts-tcp-ft"

  # https://github.com/hikhvar/ts3exporter
  # Docker Image: https://github.com/ricardbejarano/ts3exporter
  teamspeak-exporter:
    image: ricardbejarano/ts3exporter:latest
    #image: ghcr.io/hikhvar/ts3exporter:latest
    #build:
    #  context: https://github.com/hikhvar/ts3exporter.git#:/
    #  dockerfile: Dockerfile
    container_name: teamspeak-exporter
    restart: unless-stopped
    #ports:
    #  - 127.0.0.1:9189:9189/tcp
    #volumes:
    #  - /config_teamspeak-exporter/serveradmin_password.txt:/etc/ts3exporter/password:ro
    environment:
      SERVERQUERY_PASSWORD: "passw0rd"
    command:
      - "-enablechannelmetrics=true"
      #- "-ignorefloodlimits=false" # Use this only if your exporter is whitelisted in the query_ip_whitelist.txt file.
      #- "-listen=:9189"
      #- "-passwordfile=/etc/ts3exporter/password" # or use env SERVERQUERY_PASSWORD
      - "-remote=teamspeak:10011"
      - "-user=serveradmin"
    depends_on:
      - teamspeak

networks:
  default:
    external: true
    name: mynetwork
