# GITEA Actions: https://docs.gitea.com/usage/actions/overview
name: 'build docker images: example'

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shell-Script
        id: script
        run: |
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          BUILD_DATE_NUMERIC="${BUILD_DATE//[^[:digit:]]/}"
          COMMIT_HASH=${{gitea.sha}}
          COMMIT_HASH=${COMMIT_HASH::8}
          GITEA_URL=${{gitea.server_url}}
          GITEA_URL=$(echo "$GITEA_URL" | awk -F/ '{print $3}' | sed 's/\/*$//')
          GITEA_REPO=${{gitea.repository}}
          GITEA_REPO=${GITEA_REPO,,}
          GITEA_REPO_SHORT=${GITEA_REPO#*/}
          GITEA_REPO_SHORT=${GITEA_REPO_SHORT#"docker-"}
          DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/${GITEA_REPO_SHORT}
          
          # Set output parameters to github action.
          echo ::set-output name=build_date::${BUILD_DATE}
          echo ::set-output name=build_date_numeric::${BUILD_DATE_NUMERIC}
          echo ::set-output name=commit_hash::${COMMIT_HASH}
          echo ::set-output name=gittea_url::${GITEA_URL}
          echo ::set-output name=gittea_repo::${GITEA_REPO}
          echo ::set-output name=docker_repo::${DOCKER_REPO}

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com | sh

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."${{steps.script.outputs.gittea_url}}"]
              insecure = true
              ca=["/etc/ssl/certs/ca-certificates.crt"]

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{steps.script.outputs.gittea_url}}
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.GIT_USER_PASSWD  }}
        # add "GIT_USER_PASSWD" to Settings->Actions->Secrets in Repository,
        # because ${{ secrets.GITEA_TOKEN}} not working :-(
        # see: https://github.com/go-gitea/gitea/issues/23642

      #- name: Login to DockerHub 
      #  uses: docker/login-action@v3
      #  with:
      #    registry: docker.io
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          build-args: |
            BUILD_DATE=${{steps.script.outputs.build_date}}
            VCS_REF=${{steps.script.outputs.commit_hash}}
          tags: |
            ${{steps.script.outputs.gittea_url}}/${{steps.script.outputs.gittea_repo}}:latest
            ${{steps.script.outputs.gittea_url}}/${{steps.script.outputs.gittea_repo}}:${{steps.script.outputs.build_date_numeric}}.${{steps.script.outputs.commit_hash}}
         #   docker.io/${{steps.script.outputs.docker_repo}}:latest