#!/bin/sh
set -e

: "${POSTGRES_USER:="postgres"}"

: "${POSTGRES_NON_SUPERUSER_USER:="myuser"}"
: "${POSTGRES_NON_SUPERUSER_PASSWORD:="pa55w0rd"}"
: "${POSTGRES_NON_SUPERUSER_DB:="${POSTGRES_NON_SUPERUSER_USER}"}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -tc \
"SELECT 1 FROM pg_catalog.pg_user WHERE usename = '${POSTGRES_NON_SUPERUSER_USER}'" \
| grep -q 1 \
|| psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<EOSQL
	CREATE ROLE ${POSTGRES_NON_SUPERUSER_USER} WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION CONNECTION LIMIT -1 PASSWORD '${POSTGRES_NON_SUPERUSER_PASSWORD}';
	CREATE DATABASE ${POSTGRES_NON_SUPERUSER_DB} WITH OWNER = ${POSTGRES_NON_SUPERUSER_USER} ENCODING = 'UTF8' CONNECTION LIMIT = -1;
	GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_NON_SUPERUSER_DB}" to ${POSTGRES_NON_SUPERUSER_USER};
EOSQL

#psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "SELECT * FROM pg_catalog.pg_user;"
