##  _  __               _             _
## | |/ /___ _   _  ___| | ___   __ _| | __
## | ' // _ \ | | |/ __| |/ _ \ / _` | |/ /
## | . \  __/ |_| | (__| | (_) | (_| |   <
## |_|\_\___|\__, |\___|_|\___/ \__,_|_|\_\
##           |___/

## Keycloak - Open Source Identity and Access Management
## https://www.keycloak.org/
## https://github.com/keycloak/keycloak
## https://hub.docker.com/r/keycloak/keycloak
## https://quay.io/repository/keycloak/keycloak
## Docs:
## * https://www.keycloak.org/getting-started/getting-started-docker
## * Container: https://www.keycloak.org/server/containers
## * All configuration: https://www.keycloak.org/server/all-config
## * Features: https://www.keycloak.org/server/features
## * healthcheck: https://www.keycloak.org/server/health
## Supported architectures: amd64, arm64
## URL: http://localhost:8080/auth
## Requirements: setup database (mariadb, postgres or other database) before start keycloak!

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env-config
  namespace: keycloak
  labels:
    app: keycloak
data:
  #TZ: Europe/Berlin
  # Database
  KC_DB: "mariadb"                                 # mariadb, postgres or other db ...
  KC_DB_URL_HOST: "keycloak-db"
  #KC_DB_URL_PORT: 3306
  # Feature
  #KC_FEATURES: "hostname:v2,docker:v1"
  #KC_FEATURES_DISABLED: ""
  # Hostname
  #KC_HOSTNAME: "auth.example.com" # Host or full url
  KC_HOSTNAME_STRICT: "false"
  # Proxy
  #KC_PROXY_PROTOCOL_ENABLED: "true"
  KC_PROXY_HEADERS: xforwarded
  # HTTP/TLS
  KC_HTTP_RELATIVE_PATH: "/auth"  # default: "/"
  KC_HTTP_ENABLED: "true"         # default: false, but we use this for Proxy
  KC_HTTP_PORT: "8080"
  #KC_HTTPS_PORT: "8443"
  #KC_HTTPS_CERTIFICATE_FILE: "/ssl/ssl.crt"      # or use KC_HTTPS_KEY_STORE_FILE
  #KC_HTTPS_CERTIFICATE_KEY_FILE: "/ssl/ssl.key"
  #KC_HTTPS_KEY_STORE_FILE: "/ssl/keystore.jks"   # or use KC_HTTPS_CERTIFICATE_FILE
  #KC_HTTPS_CIPHER_SUITES: ""
  #KC_HTTPS_PROTOCOLS: "TLSv1.3,TLSv1.2"
  #KC_HTTPS_TRUST_STORE_FILE: "/ssl/cacerts.jks"
  #KC_HTTPS_TRUST_STORE_TYPE: "jks"
  # Truststore (CA files)
  #KC_TRUSTSTORE_PATHS: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  #KC_TLS_HOSTNAME_VERIFIER: DEFAULT
  # Healt & Metrics
  KC_HEALTH_ENABLED: "true"   # :9000/auth/health
  KC_METRICS_ENABLED: "true"  # :9000/auth/metrics
  # Logging
  KC_LOG_LEVEL: "info"
  # JAVA_OPTS
  #JAVA_OPTS_APPEND: ""

---

## convert string to base64 in Linux: "echo -n 'value' | base64"

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-env-secret
  namespace: keycloak
  labels:
    app: keycloak
stringData:
  # Admin User
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "passw0rd"
  # HTTP/TLS
  #KC_HTTPS_KEY_STORE_PASSWORD: "changeit"
  #KC_HTTPS_TRUST_STORE_PASSWORD: "changeit"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      #imagePullSecrets:
      #- name: regcred
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.0
        #image: docker.io/keycloak/keycloak:26.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: keycloak-env-config
        - secretRef:
            name: keycloak-env-secret
        ## Beginning: import from Database secret ##
        env:
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-db-env-secret
              key: MARIADB_USER
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-db-env-secret
              key: MARIADB_PASSWORD
        - name: KC_DB_URL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: keycloak-db-env-config
              key: MARIADB_DATABASE
        ## END: import from Database secret ##
        args: ["start"]
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 9000
          name: management
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /auth/health/ready
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /auth/health/live
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1.0"
        volumeMounts:
        - name: cacerts-jks
          subPath: cacerts.jks
          mountPath: /ssl/cacerts.jks
          readOnly: true
        - name: keycloak-ssl
          subPath: ssl.crt
          mountPath: /ssl/ssl.crt
          readOnly: true
        - name: keycloak-ssl
          subPath: ssl.key
          mountPath: /ssl/ssl.key
          readOnly: true
      volumes:
      - name: cacerts-jks
        secret:
          secretName: cacerts-jks
          defaultMode: 420 # decimal equivalent of octal 0644
          optional: true
      - name: keycloak-ssl
        secret:
          secretName: keycloak-ssl-secret
          defaultMode: 420 # decimal equivalent of octal 0644
          optional: true

#---
#
### help to convert to base64: https://github.com/Tob1as/docker-kubernetes-collection/blob/master/examples_k8s/ca-files-secret.yaml#L8-L14
#apiVersion: v1
#kind: Secret
#metadata:
#  name: keycloak-ssl-secret
#  namespace: keycloak
#  labels:
#    app: keycloak
#type: Opaque
#data:
#  ssl.crt: <ssl.crt>
#  ssl.key: <ssl.key>

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  type: ClusterIP
  ports:
    - name: "http"
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: "https"
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: "managment"
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: keycloak

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
  annotations:
    #kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  #ingressClassName: nginx
  tls:
  - hosts:
    - auth.example.com
    secretName: ingress-tls-secret
  rules:
  - host: auth.example.com
    http:
      paths:
      - path: /auth               # https://auth.example.com/auth/
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              #name: http
              number: 8080

---

## After this line ONLY for Monitoring !

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  endpoints:
  - path: /auth/metrics
    scheme: http
    port: managment # 9000
    targetPort: 9000
  selector:
    matchLabels:
      app: keycloak  # service

#--- 
#
#apiVersion: monitoring.coreos.com/v1
#kind: PrometheusRule
#metadata:
#  name: keycloak
#  namespace: keycloak
#  labels:
#    app: keycloak
#spec:
#  groups:
#    - name: keycloak.rules
#      rules: