##  ____            _         _         _   _     ____                     _
## | __ )  __ _ ___(_) ___   / \  _   _| |_| |__ / ___|  ___  ___ _ __ ___| |_
## |  _ \ / _` / __| |/ __| / _ \| | | | __| '_ \\___ \ / _ \/ __| '__/ _ \ __|
## | |_) | (_| \__ \ | (__ / ___ \ |_| | |_| | | |___) |  __/ (__| | |  __/ |_
## |____/ \__,_|___/_|\___/_/   \_\__,_|\__|_| |_|____/ \___|\___|_|  \___|\__|
## 

## Help:
## https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
## or for a single user "admin" with password "passw0rd":
## docker run --rm -it tobi312/tools:htpasswd -bn admin passw0rd | tr -d '"\r\n' | base64

apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: default
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkMmxZNlA2MHYkdG53bzMyYTguRFNoRGdvblZES2w5MQ==
