## https://kubernetes.github.io/ingress-nginx/examples/auth/basic/

## docker run --rm -it tobi312/tools:htpasswd -bn admin passw0rd | tr -d '"\r\n' | base64

apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: default
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkMmxZNlA2MHYkdG53bzMyYTguRFNoRGdvblZES2w5MQ==
