##   ____    _        ____                     _
##  / ___|  / \      / ___|  ___  ___ _ __ ___| |_
## | |     / _ \ ____\___ \ / _ \/ __| '__/ _ \ __|
## | |___ / ___ \_____|__) |  __/ (__| | |  __/ |_
##  \____/_/   \_\   |____/ \___|\___|_|  \___|\__|
## 

## convert ssl files to base64, examples: 
## - Linux shell/bash:
##   - for i in $(find . -type f -regex ".*/.*\.\(crt\|key\|pem\)"); do echo -e "\nEncode-File $i:" ; cat $i | base64 -w0 ; done
##   - Tip: to save in file add "> ssl_convertinbase64.txt" to end of command
## - Windows PowerShell: 
##   - Get-ChildItem -Path $scriptPath -Recurse -Include *.crt,*.key,*.pem | Foreach-Object { $filename = $_.BaseName+$_.Extension ; Write-Host "$filename :" ; [System.Convert]::ToBase64String((Get-Content -Encoding Byte -Path .\$filename))}
##   - Tip: to save in file add " |  Out-File -Encoding utf8 -FilePath .\ssl_convertinbase64.txt" to end of command

apiVersion: v1
kind: Secret
metadata:
  name: ca-files-secret
  namespace: default
type: Opaque
data:
  ca.crt: <ca.crt>
  #intermediate-ca.crt: <intermediate-ca.crt>