##  ___                                 ____                     _
## |_ _|_ __   __ _ _ __ ___  ___ ___  / ___|  ___  ___ _ __ ___| |_
##  | || '_ \ / _` | '__/ _ \/ __/ __| \___ \ / _ \/ __| '__/ _ \ __|
##  | || | | | (_| | | |  __/\__ \__ \  ___) |  __/ (__| | |  __/ |_
## |___|_| |_|\__, |_|  \___||___/___/ |____/ \___|\___|_|  \___|\__|
##            |___/
## 

## https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

## secret for ingress
## convert ssl files to base64, examples: 
## - Linux shell/bash:
##   - for i in $(find . -type f -regex ".*/.*\.\(crt\|key\|pem\)"); do echo -e "\nEncode-File $i:" ; cat $i | base64 -w0 ; done
##   - Tip: to save in file add "> ssl_convertinbase64.txt" to end of command
## - Windows PowerShell: 
##   - Get-ChildItem -Path $scriptPath -Recurse -Include *.crt,*.key,*.pem | Foreach-Object { $filename = $_.BaseName+$_.Extension ; Write-Host "$filename :" ; [System.Convert]::ToBase64String((Get-Content -Encoding Byte -Path .\$filename))}
##   - Tip: to save in file add " |  Out-File -Encoding utf8 -FilePath .\ssl_convertinbase64.txt" to end of command

---

apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls-secret
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: <ssl.crt>
  tls.key: <ssl.key>
