##  ____                  _               _                             _
## / ___|  ___ _ ____   _(_) ___ ___     / \   ___ ___ ___  _   _ _ __ | |_
## \___ \ / _ \ '__\ \ / / |/ __/ _ \   / _ \ / __/ __/ _ \| | | | '_ \| __|
##  ___) |  __/ |   \ V /| | (_|  __/  / ___ \ (_| (_| (_) | |_| | | | | |_
## |____/ \___|_|    \_/ |_|\___\___| /_/   \_\___\___\___/ \__,_|_| |_|\__|
## 

## https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
## https://kubernetes.io/docs/reference/access-authn-authz/rbac/

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: myServiceAccount
  namespace: default
  labels:
    account: myAccount

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myRole
  namespace: default
  labels:
    account: myAccount
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "watch", "create"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myRoleBinding
  namespace: default
  labels:
    account: myAccount
subjects:
  - kind: ServiceAccount
    name: myServiceAccount
    namespace: default
roleRef:
  kind: Role
  name: myRole
  apiGroup: rbac.authorization.k8s.io
