# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  scrape_interval:     15s # How frequently to scrape targets by default. default: 1m
  scrape_timeout: 10s      # How long until a scrape request times out. default: 10s
  evaluation_interval: 15s # How frequently to evaluate rules. default: 1m

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'Monitoring'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - '*.rules.yml'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

#  - job_name: 'example-exporter'
#    # Override the global default and scrape targets from this job every 15 seconds.
#    scrape_interval: 15s
#    scrape_timeout: 10s
#    static_configs:
#         - targets: ['example:8080']
#    metrics_path: /metrics
#    scheme: http # or https
#    tls_config:
#      #ca_file: /ssl/ca.crt
#      insecure_skip_verify: true
#    basic_auth:
#      username: 'metrics'
#      password: 'passw0rd'
#    follow_redirects: true

  # A scrape configuration containing exactly one endpoint to scrape:
  # Here it's Prometheus itself.
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana'
    scrape_interval: 15s
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /grafana/metrics  # default: /metrics
    scheme: http
    basic_auth:
      username: 'metrics'
      password: 'passw0rd'
    follow_redirects: false

  # -------------------------------------

  - job_name: 'traefik'
    scrape_interval: 15s
    static_configs:
      - targets: ['traefik:8082']

  # -------------------------------------
      
  - job_name: 'nginx'
    scrape_interval: 15s
    static_configs:
      - targets: ['nginx-exporter:9113']

  # -------------------------------------

  # Databases

  # MariaDB
  - job_name: 'mariadb-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['mariadb-exporter:9104']
  
  # PostgreSQL
  - job_name: 'postgres-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['postgres-exporter:9187']
  
  # ElasticSearch
  - job_name: 'elasticsearch-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
  
  # MemCached
  - job_name: 'memcached-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['memcached-exporter:9150']
  
  # MongoDB
  - job_name: 'mongo-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['memcached-exporter:9216']
  
  # Redis
  - job_name: 'redis-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['redis-exporter:9121']

  # -------------------------------------

  # Messages / MQTT Broker

  # RabbitMQ
  # https://www.rabbitmq.com/prometheus.html
  - job_name: 'rabbitmq-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['rabbitmq:15692'] 

  # VerneMQ
  # https://docs.vernemq.com/monitoring/prometheus
  - job_name: 'vernemq'
    scrape_interval: 15s
    #scrape_timeout: 5s
    static_configs:
      - targets: ['vernemq:9000']  # default port: 8888
  
  # Mosquitto
  - job_name: 'mosquitto-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['mosquitto-exporter:9234']

  # -------------------------------------

  # Docker-Registry
  # https://docs.docker.com/registry/configuration/#prometheus
  - job_name: 'docker-registry'
    scrape_interval: 15s
    static_configs:
      - targets: ['docker-registry:5001']

  # -------------------------------------

  # Storages

  # MinIO 
  # https://min.io/docs/minio/container/operations/monitoring/collect-minio-metrics-using-prometheus.html#
  # docker exec -it minio mc alias list
  # docker exec -it minio mc admin prometheus generate <alias> cluster|bucket|node
#  - job_name: minio-job
#    bearer_token: TOKEN
#    metrics_path: /minio/v2/metrics/cluster
#    scheme: http
#    static_configs:
#    - targets: ['minio:9000']
#  - job_name: minio-job-node
#    bearer_token: TOKEN
#    metrics_path: /minio/v2/metrics/node
#    scheme: http
#    static_configs:
#    - targets: ['minio:9000']
#  - job_name: minio-job-bucket
#    bearer_token: TOKEN
#    metrics_path: /minio/v2/metrics/bucket
#    scheme: http
#    static_configs:
#    - targets: ['minio:9000']

  # -------------------------------------

  # Chat/Voice-Server

  # Teamspeak
  - job_name: 'teamspeak-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['teamspeak-exporter:9189']

  # -------------------------------------
