groups:
- name: Services
  rules:

  # {name=~".*node-exporter.*"}
  - alert: InstanceDown
    expr: absent(container_last_seen{name="node-exporter"}) or on (name) (time() - container_last_seen{name="node-exporter"} > 60)
    for: 1m
    labels:
      severity: warning
      service: node-exporter
    annotations:
      summary: "{{ $labels.name }} down (for {{ $value }}s)"
      description: "{{ $labels.name }} (container #{{ $labels.container_label_com_docker_compose_container_number }}) on {{ $labels.instance }} went down {{ $value }}s ago"

  - alert: InstanceDown
    expr: absent(container_last_seen{name="traefik"}) or on (name) (time() - container_last_seen{name="traefik"} > 30)
    for: 30s
    labels:
      severity: fatal
      #service: traefik
    annotations:
      summary: "{{ $labels.name }} down (for {{ $value }}s)"
      description: "{{ $labels.name }} (container #{{ $labels.container_label_com_docker_compose_container_number }}) on {{ $labels.instance }} went down {{ $value }}s ago"

  - alert: InstanceDown
    expr: absent(container_last_seen{name="postgres"}) or on (name) (time() - container_last_seen{name="postgres"} > 60)
    for: 1m
    labels:
      severity: fatal
      #service: postgres
    annotations:
      summary: "{{ $labels.name }} down (for {{ $value }}s)"
      description: "{{ $labels.name }} (container #{{ $labels.container_label_com_docker_compose_container_number }}) on {{ $labels.instance }} went down {{ $value }}s ago"

  - alert: InstanceDown
    expr: absent(container_last_seen{name="mariadb"}) or on (name) (time() - container_last_seen{name="mariadb"} > 60)
    for: 1m
    labels:
      severity: fatal
      #service: mariadb
    annotations:
      summary: "{{ $labels.name }} down (for {{ $value }}s)"
      description: "{{ $labels.name }} (container #{{ $labels.container_label_com_docker_compose_container_number }}) on {{ $labels.instance }} went down {{ $value }}s ago"

    # copy alert for other Services: "docker ps --format "{{.Names}}" | tr ' ' '\n' | sort"