#
# Docker Compose
# created 20.09.2017 by T.H.
# Todo:	
#	Change PASSWORD: root/postgres:passw0rd (PLEASE CHANGE THE DEFAULT PASSWORDS!)
#	Change Domain and E-Mail for Lets Encrypt
#	Optional: Change Timezones, List: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#	sudo mkdir -p /srv/webgis/{mysql,postgresql,nginx,ssl,html,letsencrypt}
#	sudo docker-compose up -d
#

version: "2.0"

services:

  mysql:
    image: tobi312/rpi-mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    #  MYSQL_USER: myuser
    #  MYSQL_PASSWORD: passw0rd
    #  MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      webgis:
        aliases:
         - db
        # - mariadb
  
  postgresql:
    #image: tobi312/rpi-postgresql:9.6
    image: tobi312/rpi-postgresql-postgis:9.6-2.3
    environment:
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      webgis:
        aliases:
         - postgis
         - postgres
         - pgsql
  
  phpfpm:
    #image: tobi312/rpi-php:5.6-fpm
    image: tobi312/rpi-php:7.0-fpm
    environment:
      TZ: "Europe/Berlin"
      PHP_ERRORS: 1
      #PHP_MEM_LIMIT: 128
      PHP_UPLOAD_MAX_FILESIZE: 250
      PHP_POST_MAX_SIZE: 250
      #PHP_MAX_FILE_UPLOADS: 20
    volumes:
      - ./html:/var/www/html
    networks:
      webgis:
        aliases:
         - php
         - phphost
  
  apache:
    image: tobi312/rpi-apache2:latest
    environment:
      TZ: "Europe/Berlin"
      ENABLE_PROXY_HTTP: 1
      ENABLE_PROXY_HTML: 1
      ENABLE_PROXY_FCGI: 1
      ENABLE_REWRITE: 1
      ENABLE_SSL: 1
      ALLOWOVERRIDE: 1
    #ports:
    #  - "8080:80"
    #  - "8443:443"
    volumes:
      - ./html:/var/www/html
    #  - ./ssl:/etc/ssl:ro
    networks:
      webgis:
  
  #letsencrypt:
  #  image: tobi312/rpi-certbot:latest
  #  command:  bash -c "sleep 6 && certbot certonly --standalone -d __YOUR-DOMAIN__ -d www.__YOUR-DOMAIN__ --email __YOUR-EMAIL__ --text --agree-tos --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
  #  entrypoint: ""
  #  #ports:
  #  #  - "80:80"
  #  #  - "443:443"
  #  volumes:
  #    - ./letsencrypt:/etc/letsencrypt
  #  networks:
  #    webgis:
  #      aliases:
  #       - certbot
  
  nginx:
    #image: tobi312/rpi-nginx:1.6
    #image: tobi312/rpi-nginx:1.10
    image: tobi312/rpi-nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./ssl:/etc/nginx/ssl:ro
    #  - ./html:/var/www/html
    networks:
      webgis:

networks:
  webgis:
